---
- name: Ec2 örnekleri oluşturun
  hosts: localhost
  gather_facts: false
  tasks:

  # Case, birlikte birleştirilmiş bir Görevler Grubudur
  - name: Get Info Case
    block: 
      - name: Instances bilgilerini getir
        
        ec2_instance_info:
        register: ec2info 

      - name: Print info
        debug: var="ec2info.instances"
             

    # etiketi üzerinde her zaman belirterek,
    # Bu bloğun her zaman module_default ile çalışmasına izin verdim
    # bu, güvenliğin yanlışlıkla ec2 örnekleri oluşturmaması içindir

    tags: ['always', 'getinfoonly']
  
  - ec2_vpc:
        state: present
        cidr_block: 10.0.0.0/26
        resource_tags: { "Environment":"Development" }
        region: eu-central-1

  - name: Create EC2 Case
    block: 

      - name: Launch ec2 instances
        tags: create_ec2
        ec2:
          region: eu-central-1
          key_name: case 
          group: devops-case-1
          instance_type: t2.micro
          image: ami-0d527b8c289b4af7f
          wait: yes
          wait_timeout: 500
          count: 2
          instance_tags:
            name: appservers
            os: ubuntu
          monitoring: no
          vpc_subnet_id: subnet-02fb8dc30bf8236a1
          assign_public_ip: yes
        register: ec2
        delegate_to: localhost

      - name : Instances gruba ekle
        add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
        loop: "{{ ec2.instances }}"

      - name: Wait for SSH to come up
        local_action:
          module: wait_for
          host: "{{ item.public_ip }}"
          port: 22
          delay: 10
          timeout: 120
        loop: "{{ ec2.instances }}"
    # Bu bloğun yalnızca açıkça çağrıldığında çalışmasına izin verdim
    tags: ['never', 'ec2-create']

  - name: ELB 5000
    ec2_elb_lb:
     name: case-load-balancer
    state: present
    region: eu-central-1
    zones:
      - eu-central-1a
      - eu-central-1b
    listeners:
      - protocol: http
        load_balancer_port: 5000
        instance_port: 5000
  register: elb